SELECT
    D.ID,
    D.EMAIL,
    D.FIRST_NAME,
    D.LAST_NAME
FROM
    DEVELOPERS AS D
JOIN
    SKILLCODES AS S
WHERE
    (D.SKILL_CODE & S.CODE) != 0
    AND
    S.NAME IN ('Python', 'C#')
GROUP BY
    D.ID, D.EMAIL, D.FIRST_NAME, D.LAST_NAME
ORDER BY
    D.ID ASC;